#<shared>

definitions:
  default-defaults: &default-defaults
    run:
      shell: bash

  checkout: &checkout
    uses: actions/checkout@v2
    with:
      fetch-depth: '0'

  setup-dotnet5: &setup-dotnet5
    name: Setup .NET 5
    uses: actions/setup-dotnet@v1
    with:
      dotnet-version: 5.0.x

  restore: &restore
    name: Restore
    run: dotnet restore

  build: &build
    name: Build
    run: dotnet build --configuration Release --no-restore

  run: &run
    name: Run
    run: dotnet run --configuration Release --no-restore --no-build

  empty: "hi" # fixes the yml parser from messing the last value up

#</shared>
